### ISSUE TITLE
Matched bracket highlighting is wrong, low contrast in airline

### ISSUE THREAD

**Issue by ricochet1k** [ErichDonGubler/vim-sublime-monokai#1]
![vim](https://user-images.githubusercontent.com/76901/40062351-064581ea-5829-11e8-843f-7ce026ecb900.png)

My cursor is on the `{`, but the highlight looks like it is on the `}`. I like to see the cursor highlights, but I prefer the background color to be only slightly brighter than the background.

Also, less of a problem but the airline colors make it a bit hard to read the filenames. Darker text or darker background?

**Comment by ErichDonGubler** [comment]
Hey Matt! :) Glad to see you were interested enough in my theme to try it out!

RE: brace colors: Thanks for reporting this little papercut that's bothered me too. Let's move conversation over to https://github.com/ErichDonGubler/vim-sublime-monokai/pull/2, where hopefully I have a resolution.

RE: status line colors: `vim-sublime-monokai` doesn't actually control `airline` colors with this theme. Color schemes don't normally alter this, as your `airline` colors are usually considered an orthogonal choice to the colors used by your editing pane, AFAIK.

**Comment by ErichDonGubler** [comment]
This has been resolved with commit 9e6cb20 -- since I haven't gotten any feedback, I'll close this.
