### ISSUE TITLE
IncSearch highlighting missing

### ISSUE THREAD

**Issue by diresi** [ErichDonGubler/vim-sublime-monokai#10]
I just applied the hilighting for `Search` to the `IncSearch` group because the first incremental match wasn't highlighted at all. It seems to work with this patch:
```
diff --git a/colors/sublimemonokai.vim b/colors/sublimemonokai.vim
index d3d52f173ab4..ddc3767679f7 100644
--- a/colors/sublimemonokai.vim
+++ b/colors/sublimemonokai.vim
@@ -142,7 +142,7 @@ hi! link Directory SublimeAqua
 call s:h('ErrorMsg',     { 'fg': s:black,       'bg': s:red,      'format': 'standout'     })
 hi! link FoldColumn SublimeDarkBlack
 call s:h('Folded',       { 'fg': s:warmgrey,    'bg': s:darkblack                          })
-call s:h('Incsearch',    {                                                                 })
+call s:h('IncSearch',    { 'format': 'reverse,underline'                                   })
 call s:h('LineNr',       { 'fg': s:grey,        'bg': s:lightblack                         })
 call s:h('MatchParen',   { 'format': 'underline'                                           })
 hi! link ModeMsg SublimeYellow
```

Thanks for the (otherwise) nice theme!

**Comment by jiangfangxin** [comment]
Thank you for solving this problem. I modify the theme like what you said. It works. Thank you!:smile:

**Comment by ErichDonGubler** [comment]
Interesting...I haven't run into an issue with the first highlight not being matched! I can't see a difference in behavior with the suggested snippet.

Since this seems to have resolved an issue in at least your and @jiangfangxin's cases, I think I'll just apply the suggested fix. :)
