### ISSUE TITLE
`AS` keyword in Dockerfiles get highlighted even if substring of another word

### ISSUE THREAD

**Issue by ghost** [ErichDonGubler/vim-sublime-monokai#12]
**Issue:**
The word `AS` seems to get highlighted in a `Dockerfile` regardless of case (ex: `as`) even if it's a substring of another word, not a word on its own.

**NOTE:** 
I see this happening with out of the box color schemes too... so I'm guessing this is more of a problem with default vim syntax highlighting with dockerfiles and not really this colorscheme's fault.

**How I reproduced this:**
1. On any directory without a dockerfile, `vim Dockerfile`
2. Copy the sample dockerfile snippet from below and paste it to vim
3. Sad face

**Sample Docker file:**
```
FROM mcr.microsoft.com/dotnet/core/sdk:2.1-bionic AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.1-bionic
WORKDIR /app
COPY --from=build-env /app/out .
```

**What I expect**
Only the part ` AS ` gets highlighted.

**What actually happens**
The substring `as` in `Release` and `aspnet` also get highlighted.

**My environment**
1. vim 8.1.2056
2. Terminator on my linux environment, but I reproduced this on Conemu on my WSL as well.

**Screenshots**
WSL:
![image](https://user-images.githubusercontent.com/44413051/65344445-c1432280-dba5-11e9-8f89-d80ef469c140.png)

Linux:
![image](https://user-images.githubusercontent.com/44413051/65344487-d5871f80-dba5-11e9-99f5-6ad216f9beb0.png)

Sample screenshot showing this with out of box colorscheme `elflord`
![image](https://user-images.githubusercontent.com/44413051/65344637-357dc600-dba6-11e9-8e26-abf0b7b1d82a.png)

**Comment by ghost** [comment]
Ah, googled around for this a bit, found that installing either one of these fixes the issue!  Never mind, closing.

1. https://github.com/ekalinin/Dockerfile.vim
2. https://github.com/moby/moby/tree/master/contrib/syntax/vim

<blockquote><img src="https://avatars1.githubusercontent.com/u/234891?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/ekalinin/Dockerfile.vim">ekalinin/Dockerfile.vim</a></strong></div><div>Vim syntax file & snippets for Docker's Dockerfile - ekalinin/Dockerfile.vim</div></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/27259197?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/moby/moby">moby/moby</a></strong></div><div>Moby Project - a collaborative project for the container ecosystem to assemble container-based systems - moby/moby</div></blockquote>

**Comment by ErichDonGubler** [comment]
This is a good bit of information, though! I'll add an issue to get docs updated so that more people don't get confused by this. :)

**Comment by JoeHFB** [comment]
@ErichDonGubler - I don't think this colorscheme will require any extra plugins anymore to correct the syntax highlighting.  As https://github.com/moby/moby/blob/master/contrib/syntax/vim/README.md says their `dockerfile.vim` got merged into vim, so we get it OOTB now. :) 

Just tested and it works OOTB
![image](https://user-images.githubusercontent.com/60893676/96645980-68d6db00-12f9-11eb-807e-879c6cd52227.png)


<blockquote><img src="https://avatars1.githubusercontent.com/u/27259197?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/moby/moby">moby/moby</a></strong></div><div>Moby Project - a collaborative project for the container ecosystem to assemble container-based systems - moby/moby</div></blockquote>
