### ISSUE TITLE
signcolumn color is gray and not blend well with other colors

### ISSUE THREAD

**Issue by jdhao** [ErichDonGubler/vim-sublime-monokai#16]
Thanks for this color scheme. I have found that sign column color too gray and not blend well other colors.

![image](https://user-images.githubusercontent.com/16662357/96597709-b9adfa00-1320-11eb-8cd8-7f247c2b2a52.png)

Maybe just set sign column color to that of `LineNr` or make it darker?

**Comment by ErichDonGubler** [comment]
This should be resolved with 0e3db1df89a026ddf3925f753f571b19260f789b. Thanks for the report! And 😅 thanks for being patient with my response.
