### ISSUE TITLE
it Dont work when I open the php type file

### ISSUE THREAD

**Issue by ITnpc** [ErichDonGubler/vim-sublime-monokai#5]
hi, I like it very much, but it Dont work when I open the php type file,
 Can you support php ?
Thanks a lot!

**Comment by ErichDonGubler** [comment]
How does PR https://github.com/ErichDonGubler/vim-sublime-monokai/pull/6 look? :) [Here](https://github.com/ErichDonGubler/vim-sublime-monokai/tree/daa219c) is a link to see the README with those changes.

**Comment by ErichDonGubler** [comment]
Since I've received no feedback in over a week, I'll close this. Holler if you need something else for PHP here, or feel free to open another issue!
